INSERT INTO OFFICE (NAME_OFFICE) VALUES ('Analista de Sistemas');

INSERT INTO SECTOR (NAME_SECTOR) VALUES ('Desenvolvimento');

INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, ID_SECTOR, ID_OFFICE) VALUES ('Davi', 'Santos', 1, 1);
INSERT INTO EMPLOYEE (FIRST_NAME, LAST_NAME, ID_SECTOR, ID_OFFICE) VALUES ('Maria', 'Costa', 1, 1);

INSERT INTO TASK (TITLE_TASK, DESCRIPTION_TASK, PRIORITY_TASK, TYPE_TASK, START_AT_TASK, END_AT_TASK, ID_SECTOR) VALUES ('Criar o conceito do layout', 'Deve-se criar o conteito do layout da aplicação utilizando o figma', 1, 'Criação', '2023-10-16T12:30:00', '2023-10-17T12:30:00', 1);

INSERT INTO TASK_EMPLOYEE (ID_TASK, ID_EMPLOYEE) VALUES (1, 1);
INSERT INTO TASK_EMPLOYEE (ID_TASK, ID_EMPLOYEE) VALUES (1, 2);
